In [1]:
import numpy as np

# Q1) How to create an empty and full NumPy array?

# Creating an Empty Numpy Array
- To create an empty NumPy array, we can use the numpy.empty() function.
- The empty() function in NumPy is used to create an empty array with a specified shape.
- An empty NumPy array is an array that is initialized with arbitrary values, and its shape is determined by the user.
- An array in NumPy that is empty has random values as its initial values, and the user specifies how it should be shaped.

In [2]:
emptyArray=np.empty((2,3))
print(emptyArray)

[[5.90044465e-312 5.90044465e-312 5.90044465e-312]
 [5.90044465e-312 5.90044465e-312 5.90044465e-312]]


# Create a Full Numpy Array
- To create a full NumPy array, you can use the numpy.full() function.
- The full() function in NumPy creates an array of a given shape and fills it with a specified value.
- A full NumPy array is an array where all the elements have the same predefined value.
- This is useful when you want to initialize an array with a specific value.

In [3]:
fullArray=np.full((3,5),100)
print(fullArray)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


# Q2) Create a Numpy array filled with all zeros
- Numpy.zeros() method to do this task.

In [5]:
arr=np.zeros((3,4), dtype="i")
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Q3) Create a Numpy array filled with all ones
- To create an array filled with all ones, given the shape and type of array we can use numpy.ones() method of NumPy library in Python.

In [9]:
one=np.ones((3,4),dtype="i")
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Q4) Check wheather a Numpy array contains a specified row

In [13]:
arr = np.array([[1, 2, 3, 4, 5], 
                   [6, 7, 8, 9, 10], 
                   [11, 12, 13, 14, 15], 
                   [16, 17, 18, 19, 20] 
                   ]) 

print([16,17,18,19,20] in arr.tolist())
print([16,17,18,-19,20] in arr.tolist())

True
False


# Q5) How to Remove rows in Numpy array that contains non-numeric values?

In [18]:
arr = np.array([[10.5, 22.5, 3.8], 
                  [41, np.nan, np.nan]]) 
print(arr)
ary=arr[~np.isnan(arr).any(axis=1)]
print(ary)

[[10.5 22.5  3.8]
 [41.   nan  nan]]
[[10.5 22.5  3.8]]


# Imp.
- Setting the axis=1 when performing an operation on a NumPy array will perform the operation row-wise, that is across all columns for each row

In [22]:
arr2 = np.array([[10.5, 22.5, 3.8],  
                  [23.45, 50, 78.7], 
                  [41, np.nan, np.nan]]) 

print(arr2)
print()
ary=arr2[~np.isnan(arr2).any(axis=1)]
print(ary)

[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]
 [41.     nan   nan]]

[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]]


In [27]:
arr3 = np.array([[10.5, 22.5, 3.8, 5], 
                  [23.45, 50, 78.7, 3.5], 
                  [41, np.nan, np.nan, 0], 
                  [20, 50.20, np.nan, 2.5], 
                  [18.8, 50.60, 8.8, 58.6]]) 

print(arr3)
print()
ary=arr3[~np.isnan(arr3).any(axis=1)]
print(ary)

[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [41.     nan   nan  0.  ]
 [20.   50.2    nan  2.5 ]
 [18.8  50.6   8.8  58.6 ]]

[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [18.8  50.6   8.8  58.6 ]]


# Q6) Remove single-dimensional entries from the shape of an array
- numpy.squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

In [37]:
arr=np.array([[[2,2,2],[2,2,2]]])
print(arr)
print(arr.ndim)
print("Shape=",arr.shape)
print()

arr=np.squeeze(arr)

print(arr)
print(arr.ndim)
print("Shape=",arr.shape)

[[[2 2 2]
  [2 2 2]]]
3
Shape= (1, 2, 3)

[[2 2 2]
 [2 2 2]]
2
Shape= (2, 3)


# Q7) Find the number of occurrences of a sequence in a NumPy array

In [52]:
arr = np.array([[2,8,9,4],  
                   [9,4,9,4], 
                   [4,5,9,7], 
                   [2,9,4,3]]) 
out=repr(arr).count("9, 4")
print(out)

4


Q8)Find the most frequent value in a NumPy array
--

# Single most frequent value

In [63]:

x=np.array([1,2,3,4,5,1,2,1,1,1,10,10,10,10,10])
print(x)
print("Most frequent value",np.bincount(x).argmax())

[ 1  2  3  4  5  1  2  1  1  1 10 10 10 10 10]
Most frequent value 1


# Multiple most frequent value

In [71]:
x=np.array([1,2,3,4,5,1,2,1,1,1,10,10,10,10,10,100])
y=np.bincount(x)
print(y)
maxi=max(y)

for i in range(len(y)):
    if y[i]==maxi:
        print(i,end=" ")

[0 5 2 1 1 1 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
1 10 

# Q9) Combining a one and a two-dimensional NumPy Array

In [81]:
arr1=np.arange(5)
print(arr_1)
print()
arr2=np.arange(10).reshape(2,5)
print(arr2)
print()

for a,b in np.nditer([arr1,arr2]):
    print(a,":",b)

[0 1 2 3 4]

[[0 1 2 3 4]
 [5 6 7 8 9]]

0 : 0
1 : 1
2 : 2
3 : 3
4 : 4
0 : 5
1 : 6
2 : 7
3 : 8
4 : 9


# Q10) How to build an array of all combinations of two NumPy arrays?

In [92]:
arr1=np.array([1,2,3])
arr2=np.array([6,7,8])
combine=np.array(np.meshgrid(arr1,arr2)).T.reshape(-1,3)
print(combine)

[[1 6 1]
 [7 1 8]
 [2 6 2]
 [7 2 8]
 [3 6 3]
 [7 3 8]]


# Q11) How to add a border around a NumPy array?
- Sometimes we need to add a border around a NumPy matrix. Numpy provides a function known as ‘numpy.pad()’ to construct the border. The below examples show how to construct a border of ‘0’ around the identity matrix.

In [104]:
arr=np.ones((2,2),dtype="i")
print(arr)
print()
arr=np.pad(arr,pad_width=1,mode='constant',constant_values=99)
print(arr)

[[1 1]
 [1 1]]

[[99 99 99 99]
 [99  1  1 99]
 [99  1  1 99]
 [99 99 99 99]]


In [111]:
arr=np.zeros((3,4),dtype="i")
print(arr)
print()
arr=np.pad(arr,pad_width=1,mode="constant", constant_values=1)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


# Q12) How to compare two NumPy arrays?

In [119]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
comparison=arr1==arr2
print(comparison)
equal=comparison.all()
print(equal)

[[ True  True]
 [ True  True]]
True
