NumPy
--

# What is NumPy?
- NumPy is the fundamental package for scientific computing in python.
- NumPy is a python library that provides a multidimensional array object, various derived objects.

# What is NumPy Array?
- An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.
- 1D Array, 2D Array, 3D Array

# Advantages of using NumPy Arrays Over Python List:
- Consumes less memory
- Fast as compared to python list
- convenient to use.

# Installation and Import NumPy

- Installation --> pip install numpy
- Import --> import numpy as np

In [1]:
import numpy as np

In [2]:
# List
list=[1,2,3,4,5]
print(list)
print(type(list))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
# Array
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Importance of NumPy in Python
- Wide variety of mathematical operations on arrays
- It suuplies an enormous library of high level mathematical functions that operate these arrays and matrices.
- mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transformation, basiic linear algrbra, basic statistical operations, random simulation and much more.
  

# NumPy vs Python List
- Data Types storage(list is multiple data type, but numPy doesnot allow multiple data types)
- Importing mopdule(list can use by default no need to import any package, to use array we need to import numpy)
- Numerical operation(List is slow in numerical operation, )
- Modification capabilities
- consumes less memory
- Fast as compared to Python list
- Convenient to use.

# To find the execution time of a one line code---> %timeit
# To find the execution time of a program---> %%timeit

In [4]:
%timeit [j**4 for j in range(1,9)]

739 ns ± 26.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
%timeit np.arange(1,9)**4

2.23 μs ± 75.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


NumPy Array Creation
--

In [6]:
x=[1,2,3,4,5]
a=np.array(x)
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
x=[]
for i in range(1,5):
    x.append(i)
print(x)
a=np.array(x)
print(a)

[1, 2, 3, 4]
[1 2 3 4]


# Dimensions in Arrays
- 1-D array
- 2-D array
- 3-D array
- Higher Dimensional Array

To check dimensions of the array(ndim)
--

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [9]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


# To set the dimension of the array(ndmin)

In [10]:
arrn=np.array([1,2,3,4],ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Special NumPy Array
- Array filled with 0's
- Array filled with 1's
- Create an empty array
- An array with a range of elements
- Array diagonal element filled with 1's
- Create an array with values that are spaced linearly in a specified interval

# Array filled with 0's

In [11]:
# 1D array
ar_zero=np.zeros(10)
print(ar_zero)
print(ar_zero.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [12]:
#2D array
ar_zero=np.zeros((5,5))
print(ar_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Array filled with 1's

In [13]:
ar_one=np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [14]:
ar_one=np.ones((3,4))
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Create an empty array

In [15]:
ar_empty=np.empty(7)
print(ar_empty)       #print the previous memory

[-6.95319424e-310  1.39755179e-242  7.14798568e-312  7.14798568e-312
  5.43472210e-323  9.88131292e-324  0.00000000e+000]


# An array with a range of elements

In [16]:
ar_ran=np.arange(19)
print(ar_ran)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


# Array diagonal element filled with 1's

In [17]:
ar_dig=np.eye(3)
print(ar_dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create an array with values that are spaced linearly in a specified interval

In [18]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Creating NumPy Arrays with Random Number
- rand(): The function is used to generate a random value between 0 to 1.
- randn(): The function is used to generate a random value close to zero(both +ve and -ve).
- ranf(): the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0)
- randint(): the function is used to generate a random number between a given range.
  

# rand()

In [19]:
arr=np.random.rand(5)
print(arr)
print(arr.dtype)

[0.02701759 0.88268256 0.34072209 0.45291165 0.29885795]
float64


In [20]:
var1=np.random.rand(3,5)
print(var1)

[[0.74782469 0.07751861 0.49463228 0.07884602 0.61728025]
 [0.50441487 0.69711018 0.43707137 0.3708257  0.18242145]
 [0.05317428 0.03175347 0.48098857 0.70809865 0.58449672]]


randn()
--

In [21]:
arr2=np.random.randn(10)
print(arr2)

[ 1.03425661 -0.33818052 -1.21827582  0.37213114 -1.35072432  1.39004952
  1.39375237  0.95483543  0.02275031  0.22065498]


# ranf()

In [22]:
arr3=np.random.ranf(10)
print(arr3)

[0.55510556 0.09884566 0.48037525 0.2241685  0.62536366 0.05518026
 0.12412534 0.11316556 0.50026156 0.01930634]


# randint(min,max,total_no)

In [23]:
arr3=np.random.randint(1,5,10)
print(arr3)

[4 3 3 3 2 1 1 3 3 4]


# NumPY - Data Types
- bool_  
- int_    
- intc    
- intp    
- int8
- int16
- int32
- int64
- uint8
- uint16
- uint32
- uint64
- float_
- float16
- float32
- float64
- complex_
- complex64
- complex128

# How to identify data type(var.dtype)

In [24]:
var=np.array([1,2,3,4])
print("Data Type: ",var.dtype)

Data Type:  int32


In [25]:
var=np.array([1.2,2.3,3.4,4.5])
print("Data Type: ",var.dtype)

Data Type:  float64


In [26]:
var=np.array(["A","B","C","D"])
print("Data Type: ",var.dtype)

Data Type:  <U1


In [27]:
var=np.array(["A","B","C","D",1,2,3,4])
print("Data Type: ",var.dtype)

Data Type:  <U11


# List of characters that are used to represent dtype in Numpy
- i-integer
- b-boolean
- u-unsigned integer
- f-float
- c-complex float
- m-timedelta
- M-datatime
- O-object
- S-string
- U-Unicode string
- V-the fixed chunk of memory for other types(void)

In [28]:
x=np.array([1,2,3,4],dtype="S")
print(x)

x=np.array(x,dtype="i")
print(x)

[b'1' b'2' b'3' b'4']
[1 2 3 4]


In [29]:
x3=np.array([1,2,3,4])
new=x3.astype(float)
print(new)

[1. 2. 3. 4.]


In [30]:
x3=np.array([1,2,3,4])
new=x3.astype('S')
print(new)

[b'1' b'2' b'3' b'4']


# Arithmetic Operations in array

In [31]:
arr1=np.array([1,2,3,4,5])
var_add=arr1+3
print(var_add)

[4 5 6 7 8]


In [32]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])

varadd=np.add(arr1,arr2)
print(varadd)

varadd=np.subtract(arr1,arr2)
print(varadd)

varadd=np.multiply(arr1,arr2)
print(varadd)

varadd=np.divide(arr1,arr2)
print(varadd)

varadd=np.mod(arr1,arr2)
print(varadd)

varadd=np.power(arr1,arr2)
print(varadd)

varadd=np.reciprocal(arr1,arr2)
print(varadd)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[   1    4   27  256 3125]
[1 0 0 0 0]


In [33]:
x=np.array([1,2,3,4,5,6,7,8,9])

print("min",np.min(x))
print("max",np.max(x))
print("argmin",np.argmin(x))
print("argmax",np.argmax(x))
print("sqrt",np.sqrt(x))
print("cos",np.cos(x))
print("cumsum",np.cumsum(x))

min 1
max 9
argmin 0
argmax 8
sqrt [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
cos [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
cumsum [ 1  3  6 10 15 21 28 36 45]


# Shape and Reshape in Numpy Arrays

## Shape

In [34]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
print(var.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [35]:
var1=np.array([1,2,3,4,5], ndmin=5)
print(var1)

[[[[[1 2 3 4 5]]]]]


In [36]:
print(var1.shape)

(1, 1, 1, 1, 5)


## Reshape

In [37]:
var2=np.array([1,2,3,4,5,6])
x=var2.reshape(3,2)
print(x)
y=var2.reshape(1,6)
print(y)
print(y.ndim)

z=x.reshape(-1)
print(z)
print(z.ndim)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
2
[1 2 3 4 5 6]
1


# Broadcasting NumPy Array

In [38]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3])
var3=var1+var2
print(var3)

# The dimensions of both the arays should be same 

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [150]:
var1=np.array([1,2,3])
var2=np.array([1,2,3]).reshape(3,1)
print(var1)
print()
print(var2)

print(var1+var2)

[1 2 3]

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing Numpy Array

In [41]:
arr=np.array([9,8,7,6])
print(arr[2])
print(arr[-2])

7
7


In [48]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)
print(arr.ndim)

print(arr[1,3])

[[1 2 3 4 5]
 [1 2 3 4 5]]
2
4


In [52]:
arr=np.array([[[1,2,3,4,5],[9,8,7,6,5]]])
print(arr)
print(arr.ndim)

print(arr[0,1])
print(arr[0,1,3])

[[[1 2 3 4 5]
  [9 8 7 6 5]]]
3
[9 8 7 6 5]
6


# Slicing Numpy Array

In [58]:
arr=np.array([0,1,2,3,4,5,6,7])
print(arr[1:4])
print(arr[1:])
print(arr[:5])
print(arr[::])
print(arr[::2])
print(arr[::-1])

[1 2 3]
[1 2 3 4 5 6 7]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7]
[0 2 4 6]
[7 6 5 4 3 2 1 0]


In [61]:
# In 2d Array
arr=np.array([[1,2,3,4,5,6],[9,8,7,6,5,4],[11,12,13,14,15,16]])
print(arr[2,::-1])
print(arr[1,::-1])

[16 15 14 13 12 11]
[4 5 6 7 8 9]


# Iterating NumPy Array

In [39]:
arr=np.array([1,2,3,4,5,6])

for i in arr:
    print(i)

1
2
3
4
5
6


In [46]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.ndim)
for i in arr:
    for j in i:
        print(j,end=",")
    print()

2
1,2,3,4,5,
6,7,8,9,10,


In [47]:
# Without using for loop
# use nditer() function

arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [48]:
# To get both index and data ---> ndenumerate(arr)
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.ndenumerate(arr):
    print(i)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((0, 4), 5)
((1, 0), 6)
((1, 1), 7)
((1, 2), 8)
((1, 3), 9)
((1, 4), 10)


# Copy

In [54]:
arr=np.array([1,2,3,4])
print

[1 2 3 4]
[1 2 3 4]


In [56]:
cp=arr.copy()+6
print(arr)
print(cp)

[1 2 3 4]
[ 7  8  9 10]


# View

In [62]:
arr=np.array([1,2,3,4])
vi=arr.view()

arr[2]=100
vi[3]=1000
print(arr)
print(vi)

[   1    2  100 1000]
[   1    2  100 1000]


# Join Array

In [64]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr3=np.concatenate((arr1,arr2))
print(arr3)


[1 2 3 4 5 6 7 8]


In [70]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[5,6,7,8],[1,2,3,4]])

# Add along columns
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

print()

# Add along rows
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2 3 4 5 6 7 8]
 [5 6 7 8 1 2 3 4]]

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [74]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr3=np.stack((arr1,arr2),axis=1)
print(arr3)

print()

arr3=np.stack((arr1,arr2),axis=0)
print(arr3)



[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [72]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[5,6,7,8],[1,2,3,4]])

# Add along columns
arr3=np.stack((arr1,arr2),axis=1)
print(arr3)

print()

# Add along rows
arr3=np.stack((arr1,arr2),axis=0)
print(arr3)

[[[1 2 3 4]
  [5 6 7 8]]

 [[5 6 7 8]
  [1 2 3 4]]]

[[[1 2 3 4]
  [5 6 7 8]]

 [[5 6 7 8]
  [1 2 3 4]]]


In [78]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr3=np.stack((arr1,arr2),axis=0)
arr4=np.stack((arr1,arr2),axis=1)
arr5=np.hstack((arr1,arr2))
arr6=np.vstack((arr1,arr2))
arr7=np.dstack((arr1,arr2))

print(arr3)
print()
print(arr4)
print()
print(arr5)
print()
print(arr6)
print()
print(arr7)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Split Array

In [83]:
arr=np.array([1,2,3,4,5,6])

ar=np.array_split(arr,4)
print(ar)
print(type(ar))

[array([1, 2]), array([3, 4]), array([5]), array([6])]
<class 'list'>


In [88]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar=np.array_split(arr,10)
print(ar)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32), array([], shape=(0, 5), dtype=int32)]


# search

In [40]:
arr=np.array([1,2,3,4,5,6,7,6,5,4,3,2,2,1])
x=np.where( arr== 2)
print(x) 

(array([ 1, 11, 12], dtype=int64),)


In [42]:
arr=np.array([1,2,3,4,5,6,7,6,5,4,3,2,2,1])
x=np.where( (arr%2)== 0)
print(x) 

(array([ 1,  3,  5,  7,  9, 11, 12], dtype=int64),)


# Search Sorted Array

In [52]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,23])
x=np.searchsorted(arr,100)
print(x) 

12


In [62]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,23])
x=np.searchsorted(arr,3,side="left")
print(x)

2


In [66]:
arr=np.array([1,2,3,4,5,11,23])
x=np.searchsorted(arr,[5,6,7],side="left")
print(x)

[4 5 5]


# Sort

In [67]:
arr=np.array([5,6,7,2,3,8,9,1])
print(np.sort(arr))

[1 2 3 5 6 7 8 9]


# Filter

In [69]:
arr=np.array(["a","s","d","f"])
f=[True,False,True,False]
new=arr[f]
print(new)

['a' 'd']


# Insert

In [74]:
arr=np.array([1,2,3,4,5])
print(arr)

arr2=np.insert(arr,3,100)
print(arr2)

arr3=np.insert(arr,(0,2),99)
print(arr3)

[1 2 3 4 5]
[  1   2   3 100   4   5]
[99  1  2 99  3  4  5]
